In [58]:
import pandas as pd
import numpy as np
from sklearn.naive_bayes import GaussianNB as GNB
from sklearn.naive_bayes import MultinomialNB as MNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn import preprocessing
from sklearn.metrics import accuracy_score

In [59]:
data_train= pd.read_csv("SalaryData_Train.csv")
data_train.head()

age          workclass   education  educationno        maritalstatus  \
0   39          State-gov   Bachelors           13        Never-married   
1   50   Self-emp-not-inc   Bachelors           13   Married-civ-spouse   
2   38            Private     HS-grad            9             Divorced   
3   53            Private        11th            7   Married-civ-spouse   
4   28            Private   Bachelors           13   Married-civ-spouse   

           occupation    relationship    race      sex  capitalgain  \
0        Adm-clerical   Not-in-family   White     Male         2174   
1     Exec-managerial         Husband   White     Male            0   
2   Handlers-cleaners   Not-in-family   White     Male            0   
3   Handlers-cleaners         Husband   Black     Male            0   
4      Prof-specialty            Wife   Black   Female            0   

   capitalloss  hoursperweek          native  Salary  
0            0            40   United-States   <=50K  
1            0            13   United-States   <=50K  
2            0            40   United-States   <=50K  
3            0            40   United-States   <=50K  
4            0            40            Cuba   <=50K

In [60]:
data_train.shape

(30161, 14)

In [61]:
data_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30161 entries, 0 to 30160
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   age            30161 non-null  int64 
 1   workclass      30161 non-null  object
 2   education      30161 non-null  object
 3   educationno    30161 non-null  int64 
 4   maritalstatus  30161 non-null  object
 5   occupation     30161 non-null  object
 6   relationship   30161 non-null  object
 7   race           30161 non-null  object
 8   sex            30161 non-null  object
 9   capitalgain    30161 non-null  int64 
 10  capitalloss    30161 non-null  int64 
 11  hoursperweek   30161 non-null  int64 
 12  native         30161 non-null  object
 13  Salary         30161 non-null  object
dtypes: int64(5), object(9)
memory usage: 3.2+ MB


In [62]:
data_train.describe()

age   educationno   capitalgain   capitalloss  hoursperweek
count  30161.000000  30161.000000  30161.000000  30161.000000  30161.000000
mean      38.438115     10.121316   1092.044064     88.302311     40.931269
std       13.134830      2.550037   7406.466611    404.121321     11.980182
min       17.000000      1.000000      0.000000      0.000000      1.000000
25%       28.000000      9.000000      0.000000      0.000000     40.000000
50%       37.000000     10.000000      0.000000      0.000000     40.000000
75%       47.000000     13.000000      0.000000      0.000000     45.000000
max       90.000000     16.000000  99999.000000   4356.000000     99.000000

In [63]:
data_test = pd.read_csv("SalaryData_Test.csv")
data_test.head()

age   workclass      education  educationno        maritalstatus  \
0   25     Private           11th            7        Never-married   
1   38     Private        HS-grad            9   Married-civ-spouse   
2   28   Local-gov     Assoc-acdm           12   Married-civ-spouse   
3   44     Private   Some-college           10   Married-civ-spouse   
4   34     Private           10th            6        Never-married   

           occupation    relationship    race    sex  capitalgain  \
0   Machine-op-inspct       Own-child   Black   Male            0   
1     Farming-fishing         Husband   White   Male            0   
2     Protective-serv         Husband   White   Male            0   
3   Machine-op-inspct         Husband   Black   Male         7688   
4       Other-service   Not-in-family   White   Male            0   

   capitalloss  hoursperweek          native  Salary  
0            0            40   United-States   <=50K  
1            0            50   United-States   <=50K  
2            0            40   United-States    >50K  
3            0            40   United-States    >50K  
4            0            30   United-States   <=50K

In [64]:
string_columns = ["workclass","education","maritalstatus","occupation","relationship","race","sex","native"]

In [65]:
number = preprocessing.LabelEncoder()
for i in string_columns:
    data_train[i] = number.fit_transform(data_train[i])
    data_test[i] = number.fit_transform(data_test[i])

In [66]:
data_train

age  workclass  education  educationno  maritalstatus  occupation  \
0       39          5          9           13              4           0   
1       50          4          9           13              2           3   
2       38          2         11            9              0           5   
3       53          2          1            7              2           5   
4       28          2          9           13              2           9   
...    ...        ...        ...          ...            ...         ...   
30156   27          2          7           12              2          12   
30157   40          2         11            9              2           6   
30158   58          2         11            9              6           0   
30159   22          2         11            9              4           0   
30160   52          3         11            9              2           3   

       relationship  race  sex  capitalgain  capitalloss  hoursperweek  \
0                 1     4    1         2174            0            40   
1                 0     4    1            0            0            13   
2                 1     4    1            0            0            40   
3                 0     2    1            0            0            40   
4                 5     2    0            0            0            40   
...             ...   ...  ...          ...          ...           ...   
30156             5     4    0            0            0            38   
30157             0     4    1            0            0            40   
30158             4     4    0            0            0            40   
30159             3     4    1            0            0            20   
30160             5     4    0        15024            0            40   

       native  Salary  
0          37   <=50K  
1          37   <=50K  
2          37   <=50K  
3          37   <=50K  
4           4   <=50K  
...       ...     ...  
30156      37   <=50K  
30157      37    >50K  
30158      37   <=50K  
30159      37   <=50K  
30160      37    >50K  

[30161 rows x 14 columns]

In [67]:
data_test

age  workclass  education  educationno  maritalstatus  occupation  \
0       25          2          1            7              4           6   
1       38          2         11            9              2           4   
2       28          1          7           12              2          10   
3       44          2         15           10              2           6   
4       34          2          0            6              4           7   
...    ...        ...        ...          ...            ...         ...   
15055   33          2          9           13              4           9   
15056   39          2          9           13              0           9   
15057   38          2          9           13              2           9   
15058   44          2          9           13              0           0   
15059   35          3          9           13              2           3   

       relationship  race  sex  capitalgain  capitalloss  hoursperweek  \
0                 3     2    1            0            0            40   
1                 0     4    1            0            0            50   
2                 0     4    1            0            0            40   
3                 0     2    1         7688            0            40   
4                 1     4    1            0            0            30   
...             ...   ...  ...          ...          ...           ...   
15055             3     4    1            0            0            40   
15056             1     4    0            0            0            36   
15057             0     4    1            0            0            50   
15058             3     1    1         5455            0            40   
15059             0     4    1            0            0            60   

       native  Salary  
0          37   <=50K  
1          37   <=50K  
2          37    >50K  
3          37    >50K  
4          37   <=50K  
...       ...     ...  
15055      37   <=50K  
15056      37   <=50K  
15057      37   <=50K  
15058      37   <=50K  
15059      37    >50K  

[15060 rows x 14 columns]

In [68]:
colnames = data_train.columns

In [69]:
len(colnames[0:13])
trainX = data_train.iloc[:,:-1]
trainY = data_train.iloc[:,-1]
testX = data_test.iloc[:,:-1]
testY = data_test.iloc[:,-1]
trainX.shape,trainY.shape,testX.shape,testY.shape

((30161, 13), (30161,), (15060, 13), (15060,))

# Multinomial NB

In [70]:
mb = MNB()
mb.fit(trainX,trainY)

MultinomialNB()

In [71]:
train_salary_predMB = mb.predict(trainX)
train_salary_predMB

array([' >50K', ' <=50K', ' <=50K', ..., ' <=50K', ' <=50K', ' >50K'],
      dtype='<U6')

In [72]:
accuracy_score(train_salary_predMB,trainY)

0.7729186698053778

In [73]:
confusion_matrix(train_salary_predMB,trainY)

array([[21717,  5913],
       [  936,  1595]], dtype=int64)

In [74]:
mb.fit(testX,testY)

MultinomialNB()

In [75]:
test_salary_predMB = mb.predict(testX)
test_salary_predMB

array([' <=50K', ' <=50K', ' <=50K', ..., ' <=50K', ' >50K', ' <=50K'],
      dtype='<U6')

In [76]:
accuracy_score(test_salary_predMB,testY)

0.7749667994687915

In [77]:
confusion_matrix(test_salary_predMB,testY)

array([[10891,  2920],
       [  469,   780]], dtype=int64)

# Gaussian NB

In [78]:
nb = GNB()
nb

GaussianNB()

In [79]:
nb.fit(trainX,trainY)

GaussianNB()

In [80]:
train_salary_predNB = nb.predict(trainX)
train_salary_predNB

array([' <=50K', ' <=50K', ' <=50K', ..., ' <=50K', ' <=50K', ' >50K'],
      dtype='<U6')

In [81]:
accuracy_score(train_salary_predNB,trainY)

0.7953317197705646

In [82]:
confusion_matrix(train_salary_predNB,trainY)

array([[21505,  5025],
       [ 1148,  2483]], dtype=int64)

In [83]:
test_salary_predNB = nb.predict(testX)
test_salary_predNB

array([' <=50K', ' <=50K', ' <=50K', ..., ' <=50K', ' >50K', ' <=50K'],
      dtype='<U6')

In [84]:
accuracy_score(test_salary_predNB,testY)

0.7946879150066402

In [85]:
confusion_matrix(test_salary_predNB,testY)

array([[10759,  2491],
       [  601,  1209]], dtype=int64)

##### So from above two gaussian and multinomial bayes we conclude that Guassian gives better accuracy as expected